"""removed participants from kookkie session

Revision ID: d167a4a5d3b2
Revises: a6f6a1a834c9
Create Date: 2023-07-10 14:24:10.207007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd167a4a5d3b2'
down_revision = 'a6f6a1a834c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kookkie_participant')
    with op.batch_alter_table('kookkie_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kookkie_session', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.create_table('kookkie_participant',
    sa.Column('id', sa.VARCHAR(length=40), nullable=False),
    sa.Column('joining_id', sa.VARCHAR(length=40), nullable=True),
    sa.Column('kookkie_session_id', sa.VARCHAR(length=40), nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), nullable=True),
    sa.ForeignKeyConstraint(['kookkie_session_id'], ['kookkie_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
